name: esp32c3

on:
  push:
    branches:
      - esp32c3
    # paths:
    #   - '**.yml'
    #   - '**.json'
    #   - '**.py'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        targets:
          - "esp32c3"
        examples:
          - "gpio"
        idf-branch: ["release/v5.0"] 
        os: [ubuntu-latest]  
        python-version: [3.9]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
        - uses: actions/checkout@v2
          with:
            submodules: "recursive"

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install
          if: matrix.os == 'ubuntu-latest'
          run: |
            sudo apt install -y git wget gperf cmake ninja-build ccache dfu-util 

        - name: Build 
          run: |
            git clone -b ${{ matrix.idf-branch }} --recursive https://github.com/espressif/esp-idf.git
            cd esp-idf
            ./install.sh ${{ matrix.targets }}
            . ./export.sh
            cd ..
            cd examples/${{ matrix.examples }}
            idf.py set-target ${{ matrix.targets }}
            idf.py build
            idf.py uf2
            cd build
            esptool.py --chip esp32c3 merge_bin -o test-rainmaker-${{ matrix.targets }}-${{ matrix.examples }}.bin @flash_args

        - name: Upload-uf2
          uses: actions/upload-artifact@v2
          with:
            name: rainmaker-uf2-${{ matrix.targets }}-${{ matrix.examples }}
            path: examples/${{ matrix.examples }}/build/uf2.bin

        - name: Upload-bin
          uses: actions/upload-artifact@v2
          with:
            name: rainmaker-bin-${{ matrix.targets }}-${{ matrix.examples }}
            path: examples/${{ matrix.examples }}/build/test-rainmaker-${{ matrix.targets }}-${{ matrix.examples }}.bin
